# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a43d64a3f2cd08598dbe6b2d9c46e067be0ff69c6e040ac7aa8b1ef8372d22e61f095eb66ddada865b152e01c5b8a7d1e102a022c9fd0828f045662898052020

test:
  secret_key_base: 8c385e2a73bdd49ca230514421c008889acad36233211562e1bde500a6c23ed3e6b5688608059ca95f6a655f270d4a7f1ec6e50898d4b7045eb2bfbed79312ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
